server:
  port: 8080

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://cloverdb.cbe4g42wmxst.ap-northeast-2.rds.amazonaws.com:3306/surfer
    username: cloverdb
    password: cloverdb
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  servlet:
    multipart:
      enabled: true

logging:
  level:
    root: INFO