server:
  port: 8080

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://3.35.227.202:3306/surfer
    username: clover
    password: clover
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

logging:
  level:
    root: INFO